### ISSUE TITLE
Pink Salt Blocks are not seen on both Xaero's maps

### ISSUE THREAD

**Issue by SimulationOfMario** [0rc1nus/Galosphere-Main#105]
The pink salt caves are simply not seen on the maps because the blocks are not displayed, no pink representation of the blocks is seen.

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions

**Comment by SimulationOfMario** [comment]
hey! 1.4.2 is only avaible for 1.21, so sad! (I'm playing in 1.20.1)
But glad to help you!
