### ISSUE TITLE
[Galosphere Forge 1.20.1] Recipes don't use tags

### ISSUE THREAD

**Issue by Qwerty97475** [0rc1nus/Galosphere-Main#114]
Recipes such as the Silver Balance don't use a #forge:ingot/X tag, but rather galosphere:silver_ingot, which means only Galosphere's ingots can be used to craft these items. Other recipes with mistakes such as this do exist as well.

**Comment by Qwerty97475** [comment]
Those recipes are: silver lattice, barometer, silver upgrade smithing template, shadow frame, silver balance, and pink salt lamp

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions
