### ISSUE TITLE
Berserker spawning preserved in certain cases crashes the game

### ISSUE THREAD

**Issue by sauphle** [0rc1nus/Galosphere-Main#118]
If a berserker tries to spawn preserved, but there's no valid spawn locations the game crashes.

[crash-2024-11-02_09.28.21-server.txt](https://github.com/user-attachments/files/17607268/crash-2024-11-02_09.28.21-server.txt)

Forge 47.3.11
Minecraft 1.20.1
Galosphere 1.4.1

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions
