### ISSUE TITLE
Preserved Upgrade Smithing Template isn't able to be copied

### ISSUE THREAD

**Issue by PuppySnot** [0rc1nus/Galosphere-Main#122]
As the title suggests, I am not able to copy the smithing template the way you would with other templates. I tried using 7 Diamonds, 1 Pink Salt Shard, and the Preserved Upgrade template and it would not allow it to be copied. I made sure I had the crafting setup correct, but tried a number of variations to make sure. I am not sure if it is supposed to be able to be copied or not, but if it is please tell me if I am doing it incorrectly. I tried looking this up beforehand but the modpack information on Curseforge and anywhere that isn't your discord (haven't joined it but maybe there's info there?) is very lacking. Also a lot of your images that are in the description section don't load on the Curseforge site (at least for me). Thank you!

**Comment by 0rc1nus** [comment]
You can't duplicate this specific template. You can join the discord here for further questions.

https://discord.gg/HSyVPZTFvF
