### ISSUE TITLE
[1.19.2 Forge] Warped Anchor sometimes consume two stacks of allurite

### ISSUE THREAD

**Issue by RedBeast1959** [0rc1nus/Galosphere-Main#19]
Forge 43.1.43
Galosphere-1.19.1-1.1.2-Forge.jar

As we know warped anchor stacks 4 blocks of allurite and when we throw ender pearl, with a cost of one stacks of allurite and ender pearl, we teleport to nearby anchor.

But sometimes, throwned ender pearl consume two stacks of allurite, making warped anchor depleted too fast.

Problem is, this bug is completely random. I think it seems probability of bug is increasing when we're running while throwing ender pearl.

**Comment by 0rc1nus** [comment]
Fixed in this version 

https://www.curseforge.com/minecraft/mc-mods/galosphere/files/4077725
