### ISSUE TITLE
[Compatibility] Silver Ore variants for the Excavated Variants mod

### ISSUE THREAD

**Issue by DarthCaesium** [0rc1nus/Galosphere-Main#20]
Would you be willing to make a config file for the mod Excavated Variants to have variants for Silver Ore? I tried to make one for myself but I'm not confident with json files. They even explain how to do so on [here](https://github.com/lukebemish/excavated_variants/blob/1.19/README.md), so if you could provide a config file to them, they could update their mod to include Silver Ore for Galosphere as well.

**Comment by Toastr125** [comment]
I'm currently using both of those mods and it appears this has been implemented, as Excavated Variants has Silver Ore variants without me changing any of its settings. Should this ticket be closed?

**Comment by DarthCaesium** [comment]
Yes.
