### ISSUE TITLE
Whatever you did in the new update it cause Galosphere biome to spawn EVERYWHERE

### ISSUE THREAD

**Issue by bugescape** [0rc1nus/Galosphere-Main#25]
Please revet any changes you did about the spawn rate, now Galosphere biome just spawn everywhere in a world, wherever you dig down you can always find Galosphere biome, confirmed with spectator mode, it's spawn rates is at least 90%!

at first it looks cool, but now it just a complete infections

**Comment by bugescape** [comment]
@0rc1nus whats wrong with you? fix your mod!

**Comment by 0rc1nus** [comment]
which cave biomes are you talking about lol

**Comment by bugescape** [comment]
![image](https://user-images.githubusercontent.com/38308944/203227722-fe9a7250-50c0-45f5-b11d-3729d25b4903.png)

The biome in the mod title branding, image whenever you go underground in spectator it looks like this underground, something is wrong with the generation chance

**Comment by 0rc1nus** [comment]
Would you mind giving me the world seed and coordinates? It would help me out a lot

**Comment by bugescape** [comment]
ASKDJaskjhdbASKJDBGvv

this is the world seed, those biome spawn everywhere near 0 0 0
