### ISSUE TITLE
Galosphere 1.20.1 - 1.3.1 DEDICATED SERVER CRASH

### ISSUE THREAD

**Issue by TheWitherlord** [0rc1nus/Galosphere-Main#51]
Crash when loading with a dedicated server on FORGE 1.20.1 - 47.1.0 

Link to log (error starts on line 211)
https://gist.github.com/TheWitherlord/bc6f0ede92457c4e8c37939f5428f5e6

**Comment by 0rc1nus** [comment]
Fixed in version 1.3.2 

https://modrinth.com/mod/galosphere/version/1.3.2
