### ISSUE TITLE
[Fabric][1.3.1] Does not start and says that fabric is not installed

### ISSUE THREAD

**Issue by Jerhom3** [0rc1nus/Galosphere-Main#69]
Fabric version
0.15.0

Unknown issues causes the mod to not recognise fabric is installed

[2023-12-02-2.log](https://github.com/0rc1nus/Galosphere-Main/files/13529735/2023-12-02-2.log)

**Comment by steve-the-player** [comment]
Do you have Fabric API installed?

**Comment by Jerhom3** [comment]
If i recall correctly, yes, ill try readding it into my modpack again and see if it'll run

**Comment by Jerhom3** [comment]
It works now lmao. I think Fabric API wasnt installed when this report was made
