### ISSUE TITLE
Missing biome tags

### ISSUE THREAD

**Issue by Mechalopa** [0rc1nus/Galosphere-Main#75]
Pink salt caves is not registered in `minecraft:is_overworld`, `minecraft:stronghold_biased_to`, `minecraft:has_structure/mineshaft`, `minecraft:has_structure/ruined_portal_standard`, and `forge:is_cave` biome tags.

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions
