### ISSUE TITLE
Latest Galosphere crash with Mod "Soulbound Enchantment"

### ISSUE THREAD

**Issue by bons66** [0rc1nus/Galosphere-Main#78]
MC 1.21.1 / Fabric 0.15.3

architectury-9.1.12-fabric.jar
cloth-config-11.1.118-fabric.jar
fabric-api-0.91.0+1.20.1.jar
jei-1.20.1-fabric-15.2.0.27.jar
modmenu-7.2.2.jar
**Galosphere-1.20.1-1.4.1-Fabric.jar**
**_[Soulbound-Fabric-0.6+1.20.1.jar](https://modrinth.com/mod/soulbound-enchantment)_**

[latest.log](https://github.com/0rc1nus/Galosphere-Main/files/13780444/latest.log)

**Galosphere-1.20.1-1.3.1-Fabric.jar**
Work fine -
[latest.log](https://github.com/0rc1nus/Galosphere-Main/files/13780451/latest.log)

**Comment by SooarynAC** [comment]
I've had the same problem. It seems to be a mixin conflict on "InventoryMixin" since both mods add keeping items on death through enchantments and smithing templates.

**Comment by bons66** [comment]
Update soulbound-fabric-1.0.0+1.20.1 fix this problem
