### ISSUE TITLE
Glimmering Weald from Quark doesn't generate when Galosphere is installed

### ISSUE THREAD

**Issue by asdasdasadg** [0rc1nus/Galosphere-Main#8]

**Comment by 0rc1nus** [comment]
Glimmering Weald seems to be generating for me. Have you tried locating the glimmering weald beneath the surface?

**Comment by asdasdasadg** [comment]
> Glimmering Weald seems to be generating for me. Have you tried locating the glimmering weald beneath the surface?

yeah just tried and it worked. didn't know /locatebiome worked like that I apologize

**Comment by 0rc1nus** [comment]
No worries
