### ISSUE TITLE
1.4.1 Dedicated server crash - Bound must be positive

### ISSUE THREAD

**Issue by Fureniku** [0rc1nus/Galosphere-Main#81]
I run a private server with a few friends. A friend was exploring a new area and tried to fight a Berserker, and it crashed the server.

Unfortunately that's all the information I have but I can pass on any questions if you need more info!

[crash-2024-01-06_02.14.14-server.txt](https://github.com/0rc1nus/Galosphere-Main/files/13848127/crash-2024-01-06_02.14.14-server.txt)

**Comment by Kitoglav** [comment]
Also had the same problem.
There is a fix.
https://github.com/0rc1nus/Galosphere-Main/pull/99

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions
