### ISSUE TITLE
Unable to Spawn NPC's from Taterzens mod w/ Galosphere

### ISSUE THREAD

**Issue by GamerGaven** [0rc1nus/Galosphere-Main#9]
Using forge 40.1.30
Typing "/npc create" causes the command to fail as shown below.
![2022-06-14_14 08 49](https://user-images.githubusercontent.com/83141599/173691304-ffbd557b-1b58-4c6e-90f2-251c5298b894.png)

Here is the [debug.log](https://github.com/0rc1nus/Galosphere-Main/files/8904021/debug.log)

**Comment by 0rc1nus** [comment]
By the looks of it, it doesn't seem like galosphere is causing this issue. But I'll investigate this issue further.

**Comment by 0rc1nus** [comment]
Did a bit of investigation, and this seems to be working for me. Galosphere does not affect this, thanks
