### ISSUE TITLE
Silver from other mods can't be used in some crafts

### ISSUE THREAD

**Issue by 0Navis0** [0rc1nus/Galosphere-Main#90]
Silver from other mods can't be used for crafting silver block, panel, tiles, lattice, balance, barometer, shadow frame, pink salt lamp.

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions
