### ISSUE TITLE
Tick?

### ISSUE THREAD

**Issue by dheivs** [0rc1nus/Galosphere-Main#93]
Not really sure what's up but it shows the mod's name here in the crash logs: https://pastebin.com/bWxQXufG

**Comment by 0rc1nus** [comment]
Fixed in 1.4.2

Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/galosphere/files/all
Modrinth: https://modrinth.com/mod/galosphere/versions

**Comment by dheivs** [comment]
WOW!!! That was a long time ago! I can't believe it still got noticed. Thanks!
